# Generated by Django 5.1 on 2024-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coin', models.CharField(max_length=50)),
                ('Ticker', models.CharField(max_length=50)),
                ('Entry_price', models.IntegerField()),
                ('Exit_price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Take_profit', models.IntegerField()),
                ('Stop_loss', models.IntegerField()),
                ('Return_on_investment', models.IntegerField()),
                ('Entry_date', models.DateField()),
                ('Exit_date', models.DateField()),
                ('Holding_period', models.IntegerField()),
                ('Result', models.CharField(max_length=50)),
            ],
        ),
    ]
